name: Deploy to AWS Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        mvn clean package \
          --file pago-backend/pom.xml \
          -Dspring.datasource.username="${{ secrets.DB_USERNAME }}" \
          -Dspring.datasource.password="${{ secrets.DB_PASSWORD }}" \
          -Dspring.security.oauth2.client.registration.google.client-id="${{ secrets.GOOGLE_CLIENT_ID }}" \
          -Dspring.security.oauth2.client.registration.google.client-secret="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          -Dapp.auth.tokenSecret="${{ secrets.APP_TOKEN_SECRET }}" \
          -Dapp.cors.allowedOrigins="${{ secrets.APP_CORS_ALLOWED_ORIGINS }}" \
          -Dapp.oauth2.authorizedRedirectUris="${{ secrets.APP_OAUTH2_REDIRECT_URIS }}"

    - name: Set version label
      run: echo "VERSION_LABEL=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      shell: bash

    - name: Deploy to AWS Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: 'pago'
        environment_name: 'Pago-prod-env'
        version_label: ${{ env.VERSION_LABEL }}
        region: 'ap-northeast-1'
        deployment_package: pago-backend/target/pago-backend-0.0.1-SNAPSHOT.jar
