name: Deploy to AWS Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package --file pago-backend/pom.xml
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        APP_TOKEN_SECRET: ${{ secrets.APP_TOKEN_SECRET }}
        APP_CORS_ALLOWED_ORIGINS: ${{ secrets.APP_CORS_ALLOWED_ORIGINS }}
        APP_OAUTH2_REDIRECT_URIS: ${{ secrets.APP_OAUTH2_REDIRECT_URIS }}

    - name: Set version label
      run: echo "VERSION_LABEL=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      shell: bash

    - name: Deploy to AWS Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: 'pago'
        environment_name: 'Pago-env-2'
        version_label: ${{ env.VERSION_LABEL }}
        region: 'ap-northeast-1'
        deployment_package: pago-backend/target/pago-backend-0.0.1-SNAPSHOT.jar
