name: Slack Deployment Notification
on: 
  deployment_status:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ github.event.deployment_status.state }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
